# Generated by Django 2.2.13 on 2020-09-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=1024)),
                ('last_changed', models.DateTimeField(auto_now=True, verbose_name='last changed')),
            ],
            options={
                'permissions': (('can_add_procountor_token', 'Can add Procountor token'),),
            },
        ),
    ]
